import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { CategoryModal } from '@/components/Admin/CategoryModal';
import {
  useCreateInterviewCategory,
  useUpdateInterviewCategory,
} from '@/hooks/useAdmin';

jest.mock('@/hooks/useAdmin', () => ({
  useCreateInterviewCategory: jest.fn(),
  useUpdateInterviewCategory: jest.fn(),
}));

describe('CategoryModal Component', () => {
  const mockCreate = jest.fn().mockResolvedValue({});
  const mockUpdate = jest.fn().mockResolvedValue({});
  const mockOnClose = jest.fn();
  const mockOnSuccess = jest.fn();

  beforeEach(() => {
    (useCreateInterviewCategory as jest.Mock).mockReturnValue({
      mutate: mockCreate,
      isPending: false,
    });
    (useUpdateInterviewCategory as jest.Mock).mockReturnValue({
      mutate: mockUpdate,
      isPending: false,
    });
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('renders create modal correctly', () => {
    render(
      <CategoryModal
        isOpen={true}
        onClose={mockOnClose}
        category={null}
        onSuccess={mockOnSuccess}
      />
    );
    expect(screen.getByText('Add Category')).toBeInTheDocument();
  });

  it('renders edit modal correctly', () => {
    const category = {
      id: '1',
      name: 'Test',
      slug: 'test',
      systemPrompt: 'prompt',
      language: 'vi-VN',
    };
    render(
      <CategoryModal
        isOpen={true}
        onClose={mockOnClose}
        category={category}
        onSuccess={mockOnSuccess}
      />
    );
    expect(screen.getByText('Edit Category')).toBeInTheDocument();
    expect(screen.getByDisplayValue('Test')).toBeInTheDocument();
  });

  it('submits create form', async () => {
    render(
      <CategoryModal
        isOpen={true}
        onClose={mockOnClose}
        category={null}
        onSuccess={mockOnSuccess}
      />
    );

    fireEvent.change(screen.getByLabelText(/Name/i), {
      target: { value: 'New Category' },
    });
    fireEvent.change(screen.getByLabelText(/System Prompt/i), {
      target: { value: 'Prompt' },
    });

    // Slug is auto-generated but let's ensure it's set if we need to (it is auto-generated by handleNameChange)

    fireEvent.click(screen.getByText('Create'));

    await waitFor(() => {
      expect(mockCreate).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'New Category',
          slug: 'new-category',
          systemPrompt: 'Prompt',
        })
      );
    });
  });
});
